apiVersion: v1
kind: Secret
metadata:
  name: mongo-root-secret
  namespace: devops-demo
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "rootpass"
  MONGO_INITDB_DATABASE: "devopsdb"
