apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  interval: 5m
  chart:
    spec:
      chart: argocd-image-updater
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: argocd
  values:
    config:
      logLevel: info
    authScripts:
      enabled: true
