apiVersion: v1
kind: Service
metadata:
  name: devops-api-nodeport
  namespace: devops-demo
spec:
  type: NodePort
  selector:
    app: devops-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
