apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-api-config
  namespace: devops-demo
data:
  NODE_ENV: "production"
  PORT: "3000"

  # Ancien service Mongo (Deployment/Service classique)
  # MONGO_HOST: "mongo-svc"

  # Nouveau DNS Mongo (StatefulSet + Headless Service)
  MONGO_HOST: "mongo"

  MONGO_PORT: "27017"
  MONGO_DB: "devopsdb"
  MONGO_AUTH_SOURCE: "devopsdb"

  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"

