apiVersion: v1
kind: Secret
metadata:
  name: devops-api-secret
  namespace: devops-demo
type: Opaque
stringData:
  MONGO_USER: "devopsuser"
  MONGO_PASSWORD: "devopspass"
  JWT_SECRET: "change_me_very_long_secret"
