apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-deployment.yaml
  - api-service.yaml
  - api-service-nodeport.yaml
  - api-ingress.yaml
  - configmap-devops-api.yaml
  - devops-api-secret.yaml

images:
  - name: ghcr.io/samuel-elie/devops-api
    newTag: latest

