apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-api
  namespace: observability
  labels:
    release: kube-prom-stack
spec:
  namespaceSelector:
    matchNames:
      - devops-demo
  selector:
    matchLabels:
      app: devops-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
