apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: devops-api=ghcr.io/samuel-elie/devops-api
    argocd-image-updater.argoproj.io/devops-api.update-strategy: newest-build
    argocd-image-updater.argoproj.io/devops-api.allow-tags: regexp:^[0-9a-f]{40}$
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default
  source:
    repoURL: https://github.com/Samuel-elie/Devops-api.git
    targetRevision: main
    path: k8s/app
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
